apiVersion: v1
kind: Service
metadata:
  name: studentsurveyservice
spec:
  type: NodePort
  selector:
    app: studentsurvey
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 32001
