apiVersion: v1
kind: Service
metadata:
  name: studentsurveyservice
spec:
  type: NodePort
  selector:
    app: studentsurvey
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http
      nodePort: 32001
    - protocol: TCP
      port: 443
      name: https
      nodePort: 32002
